# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-PRN
version:      0.06
version_from: lib/GPS/PRN.pm
installdirs:  site
requires:
    strict:                        0
    Test::Simple:                  0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
